# Generated by Django 4.1.1 on 2022-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('idProduct', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
