# Generated by Django 4.1.1 on 2022-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='idCategory',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
