# Generated by Django 4.1.1 on 2022-10-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0002_products_idcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorysProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.CharField(max_length=500, null=True)),
                ('name_category', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
