# Generated by Django 4.1.1 on 2022-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0003_categorysproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysproduct',
            name='count_products_in_category',
            field=models.IntegerField(null=True),
        ),
    ]
