# Generated by Django 4.1.1 on 2022-10-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0005_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysproduct',
            name='id_subcategory',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorysproduct',
            name='name_subcategory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
