# Generated by Django 4.1.1 on 2022-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0006_categorysproduct_id_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name_subcategory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
