# Generated by Django 4.1.1 on 2022-10-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0007_products_name_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcatigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='categorysproduct',
            name='name_subcategory',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
