# Generated by Django 4.1.1 on 2022-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getData', '0008_subcatigory_alter_categorysproduct_name_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
