# Generated by Django 4.1.1 on 2022-10-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLylya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1000)),
                ('telephone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=100)),
                ('cart', models.TextField(null=True)),
                ('orders', models.TextField(null=True)),
            ],
        ),
    ]
