# Generated by Django 4.1.1 on 2022-10-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id_orders', models.IntegerField()),
                ('delivery', models.BooleanField()),
                ('_id_user', models.CharField(max_length=25)),
                ('products', models.TextField()),
                ('_id_courier', models.CharField(max_length=25)),
            ],
        ),
    ]
