# Generated by Django 4.1.1 on 2022-10-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='_id_courier',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
