# Generated by Django 4.1.1 on 2022-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders__id_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='_id_orders',
            field=models.IntegerField(null=True),
        ),
    ]
